### ISSUE TITLE
Resources - cannot add the googleapi stuff

### ISSUE THREAD

**Issue by Symbiot78** [Aleborg/homeassistant-aleborg-frontend#2]
Just a headsup.. 
if you're only using yaml for dashboards you cannot add resources via gui:

You are using your dashboard in YAML mode, therefore you cannot manage your resources through the UI. Manage them in configuration.yaml.

I've added it like this but honestly I don't know if it's correct:

    - url: https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Ubuntu:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap
      type: css

**Comment by Aleborg** [comment]
Do you have any other dashboard? I have one that is empty that I don't use and is hidden in the HA menu, its not in yaml mode only the Aleborg Frontend dashboard is in yaml mode. Therefore it should work to add the resource. I'll have a look at at it later today when I get back home

**Comment by Symbiot78** [comment]
Hi... I don't think I have any that's not yaml.. it's not a big deal.. just wanted to give you the info.
I'll try adding a dashboard and testing.

**Comment by Symbiot78** [comment]
tried adding a dashboard via ui.. taking control.. start with empty.. hiding..

That didn't change anything..

I would probably need to add it to configuration.yaml..

**Comment by Aleborg** [comment]
It's weird, works without problems for me.
BUT, I just noticed that thats the wrong fonts in that include, I've updated readme.md
The correct is:
`https://fonts.googleapis.com/css2?family=Exo+2:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap`
