### ISSUE TITLE
theme?

### ISSUE THREAD

**Issue by Symbiot78** [Aleborg/homeassistant-aleborg-frontend#3]
in your documentation you say a theme is included?
there's no folder but during your guide we install mushroom themes..

which are 'we' using?

**Comment by Aleborg** [comment]
This is the file used:
https://github.com/Aleborg/homeassistant-aleborg-frontend/blob/master/includes/lovelace/aleborg_frontend/common/aleborg-material.yaml

Mushroom is used for a lot the cards

**Comment by Symbiot78** [comment]
Hi Anders.. Yeah... I found that template.. but copying it to config/themes did NOT go well :) 
I assume that's not the intended way of using it?

this is what my ... try .. with your dashboard looks like.. I believe i've followed everything you've written so far.

![image](https://user-images.githubusercontent.com/3314249/224532875-cb696677-c810-4ed6-a284-5cf2e0765cc2.png)

**Comment by Aleborg** [comment]
You don't need to copy it to that folder. All the files is already placed in the correct folders, you only should need to upload them to the config folder and add the correct info in configuration.yaml

**Comment by Symbiot78** [comment]
ok. .hmm.. I wonder what I am missing then - to make it pull the template config (see above screenshot)

**Comment by Aleborg** [comment]
And you also need to edit the home.yaml for the moment to fit your needs. I will make it more generic and automated as soon as I can.

**Comment by Symbiot78** [comment]
@Aleborg  - Yeah.. I am editing home now.. I just added the 3 sensors you can see just to get some data.. but am wondering about the theme changes.. like colors etc.

**Comment by Aleborg** [comment]
Ive missed to uplod the themes folder, sorry. I'll upload it later today

**Comment by Symbiot78** [comment]
lol - Not to worry :)
I have a lot of other work I need to do with this dashboard.
I really like it for the menu etc. on the left.. Great work so far :-)

**Comment by Aleborg** [comment]
> @Aleborg - Yeah.. I am editing home now.. I just added the 3 sensors you can see just to get some data.. but am wondering about the theme changes.. like colors etc.

You'll get the correct colors when you upload the themes folder that I just uploaded.
You probably need to restart HA

**Comment by Symbiot78** [comment]
that did the trick :)

![image](https://user-images.githubusercontent.com/3314249/224553882-4c8ca54e-ce6f-4792-b464-ed889a18e186.png)
