### ISSUE TITLE
adding lights to rooms etc?

### ISSUE THREAD

**Issue by Symbiot78** [Aleborg/homeassistant-aleborg-frontend#4]
Hi

am trying to understand how to add lights/devices to rooms.
I think it's something simple.. I have all devices/entities added to rooms.
Room names match the settings.
But clicking the "all lights" for instance.. gives me 0 entities or devices.
each room also shows 0 entities.

I have checked the prereqs and i have all the cards etc installed.

Not sure where I am missing something.. perhaps you have an idea?

**Comment by Symbiot78** [comment]
Creating a autoentites card in another dashboard with light domain shows all my lights. So definitely something I am missing in the dashboard files.

**Comment by Symbiot78** [comment]
That’s just it. They do match. I have one area in HA: kitchen

in settings.yaml I have a room with areaId: “kitchen”

But nothing shows up

if I go to the ‘belysning’ page it is also completely empty

**Comment by Symbiot78** [comment]
Wait…. 

Both title AND areaID must match the HA area?

**Comment by Symbiot78** [comment]
so.. both have to match.. that's confirmed.

Now I am facing something that is missing I think:

![image](https://user-images.githubusercontent.com/3314249/234334712-c85d34e2-1736-426c-9b87-93431ca19c03.png)

**Comment by Aleborg** [comment]
I seem to have missed one frontend card, install this in hacs: https://github.com/AnthonMS/my-cards
I've added it to the readme now

**Comment by Symbiot78** [comment]
That helped after a few Ctrl+F5👌👌
